version: "3.8"
services:
  wbms-db:
    image: "bitnami/mariadb"
    restart: always
    ports:
      - 33061:3306

    environment:
      MARIADB_ROOT_USER: wbms_dba
      MARIADB_ROOT_PASSWORD: P@ss3031323334
      MARIADB_USER: wbms_dbu
      MARIADB_PASSWORD: 3031323334
      MARIADB_DATABASE: wbms

      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: wbms_dbr
      MARIADB_REPLICATION_PASSWORD: 3031323334

      MARIADB_EXTRA_FLAGS: --innodb_strict_mode=0 --innodb_log_file_size=512M --innodb_log_buffer_size=256M

    volumes:
      - d:/armin/database/mariadb-data-pks04:/bitnami/mariadb
      # - ./database/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
    networks:
      - armin-net

  wbms-backend:
    image: "mromzy/wbms-backend:0.30.01"
    depends_on:
      - wbms-db
    restart: always
    ports:
      - 6001:6001

    environment:
      WBMS_APP_PORT: "6001"

      WBMS_DB_DOMAIN: "wbms-db"
      WBMS_DB_PORT: "3306"
      WBMS_DB_USER: "wbms_dbu"
      WBMS_DB_PASSWORD: "3031323334"
      WBMS_DB_NAME: "wbms"

      # 1: PKS, 2: T30, 3: BULKING
      WBMS_SITE_TYPE: "1"

      WBMS_WB_PORT: "9001"
      WBMS_WB_MIN_WEIGHT: 1
      WBMS_WB_STABLE_PERIOD: 3000

      WBMS_SEMAI_API_KEY: "lg8EzYBtTVJnBuTSjQIJkChoDNlGMpso"
      # WBMS_SEMAI_API_URL: "http://host.docker.internal:14080/external-channel"
      WBMS_SEMAI_API_URL: "https://dispatch-api-dev.semaigroup.com/external-channel"
      WBMS_SEMAI_CERT: "./cert/pks4.wb.cert.pem"
      WBMS_SEMAI_KEY: "./cert/pks4.wb.key.pem"

    networks:
      - armin-net

  wbms-fo:
    image: "mromzy/wbms-fo:0.28.01"
    restart: always
    ports:
      - 8000:3000

    networks:
      - armin-net

  wbms-phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    networks:
      - armin-net

networks:
  armin-net:
    driver: bridge
